// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package exporter

import (
	"github.com/google/wire"
	"github.com/shaninalex/practice-wire/internal/domain"
)

// Injectors from wire.go:

func ProvideJSONExporter(storage domain.IStorage) domain.IExporter {
	jsonExporter := NewJSONExporter(storage)
	return jsonExporter
}

func ProvideCSVExporter(storage domain.IStorage) domain.IExporter {
	csvExporter := NewCSVExporter(storage)
	return csvExporter
}

func ProvideXMLExporter(storage domain.IStorage) domain.IExporter {
	xmlExporter := NewXMLExporter(storage)
	return xmlExporter
}

func ProvideMarkdownExporter(storage domain.IStorage) domain.IExporter {
	markdownExporter := NewMarkdownExporter(storage)
	return markdownExporter
}

// wire.go:

var (
	WireJSON = wire.NewSet(
		NewJSONExporter, wire.Bind(new(domain.IExporter), new(*JSONExporter)),
	)

	WireCSV = wire.NewSet(
		NewCSVExporter, wire.Bind(new(domain.IExporter), new(*CSVExporter)),
	)

	WireXML = wire.NewSet(
		NewXMLExporter, wire.Bind(new(domain.IExporter), new(*XMLExporter)),
	)

	WireMarkdown = wire.NewSet(
		NewMarkdownExporter, wire.Bind(new(domain.IExporter), new(*MarkdownExporter)),
	)
)
